[project]
name = "tbank-synth"
version = "0.1.0"
description = "Synthetic data generator for T-Bank logo detection"
dependencies = [
    "albumentations",
    "pillow",
    "numpy",
    "tqdm",
    "requests",
]
requires-python = ">=3.10"